//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoPilot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoPilot.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add fuel.
        /// </summary>
        public static string AddFuel {
            get {
                return ResourceManager.GetString("AddFuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add repair.
        /// </summary>
        public static string AddRepair {
            get {
                return ResourceManager.GetString("AddRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to really end application? Video recording will be finished!.
        /// </summary>
        public static string AppEndDescription {
            get {
                return ResourceManager.GetString("AppEndDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit application?.
        /// </summary>
        public static string AppEndTitle {
            get {
                return ResourceManager.GetString("AppEndTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string AverageConsumption {
            get {
                return ResourceManager.GetString("AverageConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow backup on start.
        /// </summary>
        public static string BackupAllowOnStart {
            get {
                return ResourceManager.GetString("BackupAllowOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send email after backup.
        /// </summary>
        public static string BackupAllowSendEmail {
            get {
                return ResourceManager.GetString("BackupAllowSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email adress.
        /// </summary>
        public static string BackupAllowSendEmailText {
            get {
                return ResourceManager.GetString("BackupAllowSendEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really wan to load this backup? This action is not reversable!.
        /// </summary>
        public static string BackupApplyDescription {
            get {
                return ResourceManager.GetString("BackupApplyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply backup from {0}?.
        /// </summary>
        public static string BackupApplyTitle {
            get {
                return ResourceManager.GetString("BackupApplyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current backup id.
        /// </summary>
        public static string BackupCurrentId {
            get {
                return ResourceManager.GetString("BackupCurrentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When selecting automatic backups, backup only save the main configuration file with settings and data. Videos and photos are not automatically included in the backup and you must manually back up only on WiFi connection. Backup video files can take a long time!.
        /// </summary>
        public static string BackupDescription {
            get {
                return ResourceManager.GetString("BackupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download into device.
        /// </summary>
        public static string BackupDownload {
            get {
                return ResourceManager.GetString("BackupDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup main data.
        /// </summary>
        public static string BackupMainFile {
            get {
                return ResourceManager.GetString("BackupMainFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup file with given id not found on server..
        /// </summary>
        public static string BackupNotFoundDescription {
            get {
                return ResourceManager.GetString("BackupNotFoundDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup not found.
        /// </summary>
        public static string BackupNotFoundTitle {
            get {
                return ResourceManager.GetString("BackupNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup options.
        /// </summary>
        public static string BackupOptions {
            get {
                return ResourceManager.GetString("BackupOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup selected files.
        /// </summary>
        public static string BackupSelectedFiles {
            get {
                return ResourceManager.GetString("BackupSelectedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no backup.
        /// </summary>
        public static string BackupUnknown {
            get {
                return ResourceManager.GetString("BackupUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view.
        /// </summary>
        public static string BackupView {
            get {
                return ResourceManager.GetString("BackupView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obd is not allowed to use.
        /// </summary>
        public static string BluetoothIsNotAllowed {
            get {
                return ResourceManager.GetString("BluetoothIsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of files.
        /// </summary>
        public static string CountOfSelectedFiled {
            get {
                return ResourceManager.GetString("CountOfSelectedFiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency unit.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this fill record?.
        /// </summary>
        public static string DeleteFuelMessage {
            get {
                return ResourceManager.GetString("DeleteFuelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete fill.
        /// </summary>
        public static string DeleteFuelTitle {
            get {
                return ResourceManager.GetString("DeleteFuelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this repair record?.
        /// </summary>
        public static string DeleteRepairMessage {
            get {
                return ResourceManager.GetString("DeleteRepairMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete repair.
        /// </summary>
        public static string DeleteRepairTitle {
            get {
                return ResourceManager.GetString("DeleteRepairTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device not found, tap to refresh.
        /// </summary>
        public static string DeviceNotFound {
            get {
                return ResourceManager.GetString("DeviceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance unit.
        /// </summary>
        public static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download backup.
        /// </summary>
        public static string DownloadBackup {
            get {
                return ResourceManager.GetString("DownloadBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your backup id and click on button.
        /// </summary>
        public static string DownloadBackupHelp {
            get {
                return ResourceManager.GetString("DownloadBackupHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download in progress ....
        /// </summary>
        public static string DownloadInProgress {
            get {
                return ResourceManager.GetString("DownloadInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automaticaly start after connected OBD.
        /// </summary>
        public static string DriveModeActivated {
            get {
                return ResourceManager.GetString("DriveModeActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to really turn off drive mode?.
        /// </summary>
        public static string DriveModeEndDescription {
            get {
                return ResourceManager.GetString("DriveModeEndDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn off drive mode?.
        /// </summary>
        public static string DriveModeEndTitle {
            get {
                return ResourceManager.GetString("DriveModeEndTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only manually start.
        /// </summary>
        public static string DriveModeNotAllowed {
            get {
                return ResourceManager.GetString("DriveModeNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving mode.
        /// </summary>
        public static string DrivingMode {
            get {
                return ResourceManager.GetString("DrivingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File id.
        /// </summary>
        public static string EnterFileId {
            get {
                return ResourceManager.GetString("EnterFileId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but the application has encountered an unexpected error. Please help me improve the application and send me an email with an error message after next start. The application will be closed now..
        /// </summary>
        public static string ErrorDescription {
            get {
                return ResourceManager.GetString("ErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And it&apos;s down: (.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fueled.
        /// </summary>
        public static string Fueled {
            get {
                return ResourceManager.GetString("Fueled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: 14.7.
        /// </summary>
        public static string FueledExample {
            get {
                return ResourceManager.GetString("FueledExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liters.
        /// </summary>
        public static string FueledUnit {
            get {
                return ResourceManager.GetString("FueledUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel price.
        /// </summary>
        public static string FuelPrice {
            get {
                return ResourceManager.GetString("FuelPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: 1000.
        /// </summary>
        public static string FuelPriceExample {
            get {
                return ResourceManager.GetString("FuelPriceExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full tank?.
        /// </summary>
        public static string FullTank {
            get {
                return ResourceManager.GetString("FullTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gallon.
        /// </summary>
        public static string Gallon {
            get {
                return ResourceManager.GetString("Gallon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last backup.
        /// </summary>
        public static string LastBackup {
            get {
                return ResourceManager.GetString("LastBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More obd devices, tap to select one.
        /// </summary>
        public static string MoreDevices {
            get {
                return ResourceManager.GetString("MoreDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accelerator pedal position.
        /// </summary>
        public static string ObdAcceleratorPedalPosition {
            get {
                return ResourceManager.GetString("ObdAcceleratorPedalPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine load percentage.
        /// </summary>
        public static string ObdEngineLoad {
            get {
                return ResourceManager.GetString("ObdEngineLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine oil temperature.
        /// </summary>
        public static string ObdEngineOilTemperature {
            get {
                return ResourceManager.GetString("ObdEngineOilTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine reference torgue.
        /// </summary>
        public static string ObdEngineReferenceTorque {
            get {
                return ResourceManager.GetString("ObdEngineReferenceTorque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel injection timing.
        /// </summary>
        public static string ObdFuelInjectionTiming {
            get {
                return ResourceManager.GetString("ObdFuelInjectionTiming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum air flow.
        /// </summary>
        public static string ObdMaxAirFlowRate {
            get {
                return ResourceManager.GetString("ObdMaxAirFlowRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor RPM.
        /// </summary>
        public static string ObdRpm {
            get {
                return ResourceManager.GetString("ObdRpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current speed.
        /// </summary>
        public static string ObdSpeed {
            get {
                return ResourceManager.GetString("ObdSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine temperature.
        /// </summary>
        public static string ObdTemperature {
            get {
                return ResourceManager.GetString("ObdTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throttle position.
        /// </summary>
        public static string ObdThrottlePosition {
            get {
                return ResourceManager.GetString("ObdThrottlePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obd data.
        /// </summary>
        public static string ObdTitle {
            get {
                return ResourceManager.GetString("ObdTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor uptime.
        /// </summary>
        public static string ObdUptime {
            get {
                return ResourceManager.GetString("ObdUptime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odometer state.
        /// </summary>
        public static string OdometerState {
            get {
                return ResourceManager.GetString("OdometerState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: 35274.
        /// </summary>
        public static string OdometerStateExample {
            get {
                return ResourceManager.GetString("OdometerStateExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup data.
        /// </summary>
        public static string OpenBackup {
            get {
                return ResourceManager.GetString("OpenBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open backup in browser.
        /// </summary>
        public static string OpenLinkInBrowser {
            get {
                return ResourceManager.GetString("OpenLinkInBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device out of range, tap to refresh.
        /// </summary>
        public static string OutOfRangeOfDevice {
            get {
                return ResourceManager.GetString("OutOfRangeOfDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per.
        /// </summary>
        public static string Per {
            get {
                return ResourceManager.GetString("Per", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo not found on your device. If you have this file backed up, you can see him at the address below. Otherwise, the file can no longer be recovered..
        /// </summary>
        public static string PhotoNotFoundDescription {
            get {
                return ResourceManager.GetString("PhotoNotFoundDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo not found on your mobile..
        /// </summary>
        public static string PhotoNotFoundTitle {
            get {
                return ResourceManager.GetString("PhotoNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        public static string Photos {
            get {
                return ResourceManager.GetString("Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to / Unit.
        /// </summary>
        public static string PricePerLiterUnit {
            get {
                return ResourceManager.GetString("PricePerLiterUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price per unit.
        /// </summary>
        public static string PricePerUnit {
            get {
                return ResourceManager.GetString("PricePerUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: 36.6.
        /// </summary>
        public static string PricePerUnitExample {
            get {
                return ResourceManager.GetString("PricePerUnitExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiving data from device.
        /// </summary>
        public static string ReceivingDataFromObd {
            get {
                return ResourceManager.GetString("ReceivingDataFromObd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripiton.
        /// </summary>
        public static string RepairDescription {
            get {
                return ResourceManager.GetString("RepairDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair price.
        /// </summary>
        public static string RepairPrice {
            get {
                return ResourceManager.GetString("RepairPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: 1250.
        /// </summary>
        public static string RepairPriceExample {
            get {
                return ResourceManager.GetString("RepairPriceExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application was last closed with an error. Want to help us improve application and report a bug?.
        /// </summary>
        public static string ReportDescription {
            get {
                return ResourceManager.GetString("ReportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application crash report.
        /// </summary>
        public static string ReportTitle {
            get {
                return ResourceManager.GetString("ReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching ....
        /// </summary>
        public static string Searching {
            get {
                return ResourceManager.GetString("Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select obd device.
        /// </summary>
        public static string SelectObdDevice {
            get {
                return ResourceManager.GetString("SelectObdDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send backup link by email.
        /// </summary>
        public static string SendByEmail {
            get {
                return ResourceManager.GetString("SendByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is link for download your backuped data.{E}Your backup id is {0}{E}Click on {1} to start download..
        /// </summary>
        public static string SendByEmailBody {
            get {
                return ResourceManager.GetString("SendByEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link on your backup.
        /// </summary>
        public static string SendByEmailSubject {
            get {
                return ResourceManager.GetString("SendByEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service name.
        /// </summary>
        public static string ServiceName {
            get {
                return ResourceManager.GetString("ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: My Service a.s..
        /// </summary>
        public static string ServiceNameExample {
            get {
                return ResourceManager.GetString("ServiceNameExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social.
        /// </summary>
        public static string Social {
            get {
                return ResourceManager.GetString("Social", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start recording.
        /// </summary>
        public static string StartRecording {
            get {
                return ResourceManager.GetString("StartRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop recording.
        /// </summary>
        public static string StopRecording {
            get {
                return ResourceManager.GetString("StopRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a picture.
        /// </summary>
        public static string TakePicture {
            get {
                return ResourceManager.GetString("TakePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap on screen to speak.
        /// </summary>
        public static string TapOnScreenToSpeak {
            get {
                return ResourceManager.GetString("TapOnScreenToSpeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap on screen to stop recording.
        /// </summary>
        public static string TapOnScreenToStopRecording {
            get {
                return ResourceManager.GetString("TapOnScreenToStopRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car has average consumption of {0} and underwent {1} repairs..
        /// </summary>
        public static string Tile {
            get {
                return ResourceManager.GetString("Tile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Av. cons. {0}, repairs {1}.
        /// </summary>
        public static string Tile_Small {
            get {
                return ResourceManager.GetString("Tile_Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on your bluetooth by tap.
        /// </summary>
        public static string TurnOnBluetooth {
            get {
                return ResourceManager.GetString("TurnOnBluetooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup page.
        /// </summary>
        public static string Tutorial_Backup {
            get {
                return ResourceManager.GetString("Tutorial_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After clicking on the &quot;Backup&quot; in the settings page will be displayed with information about the backup. Here you will find the date of the last backup, the backup identifier and settings. 1) Whether you want to do a backup after starting the application and 2) if you want the link to send backup to email..
        /// </summary>
        public static string Tutorial_Backup_Description {
            get {
                return ResourceManager.GetString("Tutorial_Backup_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup main file menu.
        /// </summary>
        public static string Tutorial_BackupFileMenu {
            get {
                return ResourceManager.GetString("Tutorial_BackupFileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In advance of the main file displays the following menu. 1) Use this button to back up the main file 2) If the backup is created, you can refer to it in the browser (and store) or 3) let it send the email. If you have a backup identifier, you can enter 4) and then click this button to download..
        /// </summary>
        public static string Tutorial_BackupFileMenu_Description {
            get {
                return ResourceManager.GetString("Tutorial_BackupFileMenu_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup menu.
        /// </summary>
        public static string Tutorial_BackupMenu {
            get {
                return ResourceManager.GetString("Tutorial_BackupMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the side menu, you see three buttons. These are 1) a general backup, which backs up the main data file, 2) backup files and 3) backup videos. If you select automatic backup after launch, it is only a backup of the master file! Videos and pictures can be advanced manually. In the list you can see which items have not been backed up..
        /// </summary>
        public static string Tutorial_BackupMenu_Description {
            get {
                return ResourceManager.GetString("Tutorial_BackupMenu_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera menu.
        /// </summary>
        public static string Tutorial_CameraMenu {
            get {
                return ResourceManager.GetString("Tutorial_CameraMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you click on the camera menu is displayed in front of you four menu. 1) Start and stop recording, 2) Take a photo, 3) Viewing your saved videos, 4) Viewing your saved photos..
        /// </summary>
        public static string Tutorial_CameraMenu_Description {
            get {
                return ResourceManager.GetString("Tutorial_CameraMenu_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close tutorial?.
        /// </summary>
        public static string Tutorial_End {
            get {
                return ResourceManager.GetString("Tutorial_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can i have close the tutorial? You can rerun this tutorial from more menu..
        /// </summary>
        public static string Tutorial_End_Description {
            get {
                return ResourceManager.GetString("Tutorial_End_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel menu.
        /// </summary>
        public static string Tutorial_FuelMenu {
            get {
                return ResourceManager.GetString("Tutorial_FuelMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you click on the menu for refueling, appears in front of you two buttons and a list of tanking. 1) Used to record new refueling, 2) To show the average consumption and can be used to switch the display mode, 3) One entry in the list, detail can be viewed by clicking..
        /// </summary>
        public static string Tutorial_FuelMenu_Description {
            get {
                return ResourceManager.GetString("Tutorial_FuelMenu_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please take a few minutes to this tutorial..
        /// </summary>
        public static string Tutorial_Information {
            get {
                return ResourceManager.GetString("Tutorial_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main screen.
        /// </summary>
        public static string Tutorial_MainScreen {
            get {
                return ResourceManager.GetString("Tutorial_MainScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On the main screen you can see the view of the camera and the main menu..
        /// </summary>
        public static string Tutorial_MainScreen_Description_One {
            get {
                return ResourceManager.GetString("Tutorial_MainScreen_Description_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The main menu contains four main controls.  1) Camera, 2) Refueling, 3) Repairs and 4) Settings and others..
        /// </summary>
        public static string Tutorial_MainScreen_Description_Two {
            get {
                return ResourceManager.GetString("Tutorial_MainScreen_Description_Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting menu.
        /// </summary>
        public static string Tutorial_MoreMenu {
            get {
                return ResourceManager.GetString("Tutorial_MoreMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you click on the other menu (three dots), there appears in front of you a list of other settings. 1) Used to enable GPS, 2) Connect the OBD module if there are more, you can select them, 3) Is used to turn drive mode that accepts voice commands, 4) Is used for uploading or sending backup. In this menu are also buttons to set the units, links to social networks and more..
        /// </summary>
        public static string Tutorial_MoreMenu_Description {
            get {
                return ResourceManager.GetString("Tutorial_MoreMenu_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obd page.
        /// </summary>
        public static string Tutorial_ObdPage {
            get {
                return ResourceManager.GetString("Tutorial_ObdPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you click on 1) OBD button when device is connected to your mobile, you will see the actual data from the OBD module to display. All data are stored for later visualization and browsing condition of the car..
        /// </summary>
        public static string Tutorial_ObdPage_Description {
            get {
                return ResourceManager.GetString("Tutorial_ObdPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair menu.
        /// </summary>
        public static string Tutorial_RepairMenu {
            get {
                return ResourceManager.GetString("Tutorial_RepairMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you click on the menu for repairs, the button in front of you and a list of repairs. 1) Used to record new repair record, 2) One entry in the list can be viewed by clicking detail..
        /// </summary>
        public static string Tutorial_RepairMenu_Description {
            get {
                return ResourceManager.GetString("Tutorial_RepairMenu_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And that&apos;s all.
        /// </summary>
        public static string Tutorial_ThanksEnd {
            get {
                return ResourceManager.GetString("Tutorial_ThanksEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tutorial is over and you can always run the application menu..
        /// </summary>
        public static string Tutorial_ThanksEnd_Description {
            get {
                return ResourceManager.GetString("Tutorial_ThanksEnd_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for installing CoPilot..
        /// </summary>
        public static string Tutorial_ThankYou {
            get {
                return ResourceManager.GetString("Tutorial_ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        public static string Tutorial_Welcome {
            get {
                return ResourceManager.GetString("Tutorial_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is CoPilot?.
        /// </summary>
        public static string Tutorial_WhatIsIt {
            get {
                return ResourceManager.GetString("Tutorial_WhatIsIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoPilot is an application that is used to record any information about the car. You can record video, take photos, keep records of refueling and repairs. When you connect the OBD also collect important data and then view them..
        /// </summary>
        public static string Tutorial_WhatIsIt_Description {
            get {
                return ResourceManager.GetString("Tutorial_WhatIsIt_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown size.
        /// </summary>
        public static string UnknownSize {
            get {
                return ResourceManager.GetString("UnknownSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload in progress ....
        /// </summary>
        public static string UploadInProgress {
            get {
                return ResourceManager.GetString("UploadInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use gps senzor.
        /// </summary>
        public static string UseGpsSenzor {
            get {
                return ResourceManager.GetString("UseGpsSenzor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use obd device.
        /// </summary>
        public static string UseObdDevice {
            get {
                return ResourceManager.GetString("UseObdDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video not found on your device. If you have this file backed up, you can see him at the address below. Otherwise, the file can no longer be recovered..
        /// </summary>
        public static string VideoNotFoundDescription {
            get {
                return ResourceManager.GetString("VideoNotFoundDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video not found on your mobile..
        /// </summary>
        public static string VideoNotFoundTitle {
            get {
                return ResourceManager.GetString("VideoNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        public static string Videos {
            get {
                return ResourceManager.GetString("Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View fuel.
        /// </summary>
        public static string ViewFuel {
            get {
                return ResourceManager.GetString("ViewFuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View repair.
        /// </summary>
        public static string ViewRepair {
            get {
                return ResourceManager.GetString("ViewRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
